---
version: "3"
services:
  paraview-env:
    image: gnasello/paraview-env:2023-07-20
    container_name: paraview
    security_opt:
      - seccomp:unconfined # for terminal to work
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- SUBFOLDER=/ #optional
      #- TITLE=Paraview #optional
    #volumes:
      #- /path/to/directory:/config/researcher_home
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 5000:3000
    #devices:
      #- /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional